[tool.ruff]
line-length = 88
exclude = ["migrations", ".git", "venv_3.9/Lib/site-packages", "venv/Lib/site-packages"]
ignore = ["E501", "E203", "E402", "E712"]

[tool.ruff.per-file-ignores]
"venv_3.9/Lib/site-packages/yaml/serializer.py" = ["F405"]
