"""test running migrations

Revision ID: 3237e8997914
Revises: 32f1a64d06ea
Create Date: 2024-07-24 18:02:32.341388

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3237e8997914"
down_revision = "32f1a64d06ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
