"""test running migrations

Revision ID: 32f1a64d06ea
Revises: 26d2f96c355d
Create Date: 2024-07-24 18:02:10.847242

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "32f1a64d06ea"
down_revision = "26d2f96c355d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
